"""Add slug and ajouts_panier

Revision ID: 2231c85d176b
Revises: 
Create Date: 2026-06-20 00:15:54.455913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2231c85d176b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ajouts_panier', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_produits_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produits_slug'))
        batch_op.drop_column('ajouts_panier')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
